-- Add createdAt and details column to LOG_ACTIVITY safely
IF COL_LENGTH('dbo.LOG_ACTIVITY', 'createdAt') IS NULL
BEGIN
  ALTER TABLE dbo.LOG_ACTIVITY ADD createdAt DATETIME2 NOT NULL DEFAULT GETDATE();
END;

IF COL_LENGTH('dbo.LOG_ACTIVITY', 'details') IS NULL
BEGIN
  ALTER TABLE dbo.LOG_ACTIVITY ADD details NVARCHAR(MAX) NULL;
END;
