IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DT_MAILBOX_CREDENTIAL'
)
BEGIN
  CREATE TABLE DT_MAILBOX_CREDENTIAL (
    nik CHAR(8) NOT NULL CONSTRAINT PK_DT_MAILBOX_CREDENTIAL PRIMARY KEY,
    zimbraEmail NVARCHAR(255) NOT NULL,
    passwordCipher NVARCHAR(MAX) NOT NULL,
    passwordIv VARCHAR(64) NOT NULL,
    passwordTag VARCHAR(64) NOT NULL,
    authToken NVARCHAR(MAX) NULL,
    authTokenExpiresAt DATETIME2 NULL,
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_MAILBOX_CREDENTIAL_updatedAt DEFAULT SYSUTCDATETIME(),
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_MAILBOX_CREDENTIAL_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DT_MAILBOX_CREDENTIAL_USER FOREIGN KEY (nik) REFERENCES DT_USER(nik) ON DELETE CASCADE
  );
END;
