-- Google Calendar OAuth credentials (encrypted access + refresh tokens)
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DT_GOOGLE_CALENDAR_CREDENTIAL'
)
BEGIN
  CREATE TABLE DT_GOOGLE_CALENDAR_CREDENTIAL (
    id VARCHAR(36) NOT NULL CONSTRAINT PK_DT_GOOGLE_CALENDAR_CREDENTIAL PRIMARY KEY,
    nik CHAR(8) NOT NULL,
    googleEmail NVARCHAR(255) NOT NULL,
    displayName NVARCHAR(255) NULL,
    accessTokenCipher NVARCHAR(MAX) NOT NULL,
    accessTokenIv VARCHAR(64) NOT NULL,
    accessTokenTag VARCHAR(64) NOT NULL,
    refreshTokenCipher NVARCHAR(MAX) NOT NULL,
    refreshTokenIv VARCHAR(64) NOT NULL,
    refreshTokenTag VARCHAR(64) NOT NULL,
    accessTokenExpiresAt DATETIME2 NULL,
    scope NVARCHAR(512) NULL,
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_GOOGLE_CALENDAR_CREDENTIAL_updatedAt DEFAULT SYSUTCDATETIME(),
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_GOOGLE_CALENDAR_CREDENTIAL_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DT_GOOGLE_CALENDAR_CREDENTIAL_USER FOREIGN KEY (nik) REFERENCES DT_USER(nik) ON DELETE CASCADE,
    CONSTRAINT UQ_DT_GOOGLE_CALENDAR_CREDENTIAL_nik_email UNIQUE (nik, googleEmail)
  );
  CREATE INDEX IX_DT_GOOGLE_CALENDAR_CREDENTIAL_nik ON DT_GOOGLE_CALENDAR_CREDENTIAL(nik);
END;
