
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DT_ZIMBRA_GOOGLE_EVENT_SYNC'
)
BEGIN
  CREATE TABLE DT_ZIMBRA_GOOGLE_EVENT_SYNC (
    id VARCHAR(36) NOT NULL CONSTRAINT PK_DT_ZIMBRA_GOOGLE_EVENT_SYNC PRIMARY KEY,
    nik CHAR(8) NOT NULL,
    zimbraEmail NVARCHAR(255) NOT NULL,
    zimbraEventKey NVARCHAR(255) NOT NULL,
    googleEmail NVARCHAR(255) NOT NULL,
    googleCalendarId NVARCHAR(255) NOT NULL,
    googleEventId NVARCHAR(255) NOT NULL,
    title NVARCHAR(500) NOT NULL,
    startMs BIGINT NOT NULL,
    endMs BIGINT NOT NULL,
    allDay BIT NOT NULL CONSTRAINT DF_DT_ZIMBRA_GOOGLE_EVENT_SYNC_allDay DEFAULT 0,
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_ZIMBRA_GOOGLE_EVENT_SYNC_updatedAt DEFAULT SYSUTCDATETIME(),
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_ZIMBRA_GOOGLE_EVENT_SYNC_createdAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DT_ZIMBRA_GOOGLE_EVENT_SYNC_USER FOREIGN KEY (nik) REFERENCES DT_USER(nik) ON DELETE CASCADE,
    CONSTRAINT UQ_DT_ZIMBRA_GOOGLE_EVENT_SYNC UNIQUE (nik, zimbraEmail, zimbraEventKey)
  );
  CREATE INDEX IX_DT_ZIMBRA_GOOGLE_EVENT_SYNC_nik_google ON DT_ZIMBRA_GOOGLE_EVENT_SYNC(nik, googleEmail);
  CREATE INDEX IX_DT_ZIMBRA_GOOGLE_EVENT_SYNC_nik_range ON DT_ZIMBRA_GOOGLE_EVENT_SYNC(nik, startMs, endMs);
END;
