-- Push subscriptions + device fingerprint on refresh tokens
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DT_PUSH_SUBSCRIPTION'
)
BEGIN
  CREATE TABLE DT_PUSH_SUBSCRIPTION (
    id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DT_PUSH_SUBSCRIPTION PRIMARY KEY DEFAULT NEWID(),
    nik CHAR(8) NOT NULL,
    endpoint NVARCHAR(MAX) NOT NULL,
    endpointHash VARCHAR(64) NOT NULL,
    p256dh NVARCHAR(255) NOT NULL,
    auth NVARCHAR(255) NOT NULL,
    userAgent NVARCHAR(500) NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_PUSH_SUBSCRIPTION_createdAt DEFAULT SYSUTCDATETIME(),
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_PUSH_SUBSCRIPTION_updatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_DT_PUSH_SUBSCRIPTION_USER FOREIGN KEY (nik) REFERENCES DT_USER(nik) ON DELETE CASCADE,
    CONSTRAINT UQ_DT_PUSH_SUBSCRIPTION_endpointHash UNIQUE (endpointHash)
  );
  CREATE INDEX IX_DT_PUSH_SUBSCRIPTION_nik ON DT_PUSH_SUBSCRIPTION(nik);
END;

IF COL_LENGTH('LOG_REFRESH_TOKEN', 'userAgent') IS NULL
BEGIN
  ALTER TABLE LOG_REFRESH_TOKEN ADD userAgent NVARCHAR(500) NULL;
END;

IF COL_LENGTH('LOG_REFRESH_TOKEN', 'deviceHash') IS NULL
BEGIN
  ALTER TABLE LOG_REFRESH_TOKEN ADD deviceHash VARCHAR(64) NULL;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = 'IX_LOG_REFRESH_TOKEN_nik_deviceHash' AND object_id = OBJECT_ID('LOG_REFRESH_TOKEN')
)
BEGIN
  CREATE INDEX IX_LOG_REFRESH_TOKEN_nik_deviceHash ON LOG_REFRESH_TOKEN(nik, deviceHash);
END;
