-- Chat tables (Full MVP)
IF OBJECT_ID('dbo.DT_CHAT_ROOM', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DT_CHAT_ROOM (
    id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DT_CHAT_ROOM PRIMARY KEY DEFAULT NEWID(),
    type VARCHAR(10) NOT NULL,
    name VARCHAR(100) NULL,
    emoji NVARCHAR(16) NULL,
    color VARCHAR(30) NULL,
    createdBy CHAR(8) NOT NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_CHAT_ROOM_createdAt DEFAULT SYSUTCDATETIME(),
    lastMessageAt DATETIME2 NULL,
    dmKey VARCHAR(20) NULL,
    CONSTRAINT UQ_DT_CHAT_ROOM_dmKey UNIQUE (dmKey),
    CONSTRAINT FK_DT_CHAT_ROOM_createdBy FOREIGN KEY (createdBy) REFERENCES dbo.DT_USER(nik)
  );
  CREATE INDEX IX_DT_CHAT_ROOM_type ON dbo.DT_CHAT_ROOM(type);
  CREATE INDEX IX_DT_CHAT_ROOM_lastMessageAt ON dbo.DT_CHAT_ROOM(lastMessageAt);
  CREATE INDEX IX_DT_CHAT_ROOM_createdBy ON dbo.DT_CHAT_ROOM(createdBy);
END;

IF OBJECT_ID('dbo.DT_CHAT_MEMBER', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DT_CHAT_MEMBER (
    roomId UNIQUEIDENTIFIER NOT NULL,
    nik CHAR(8) NOT NULL,
    role VARCHAR(10) NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_role DEFAULT 'member',
    joinedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_joinedAt DEFAULT SYSUTCDATETIME(),
    isPinned BIT NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_isPinned DEFAULT 0,
    isMuted BIT NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_isMuted DEFAULT 0,
    showTaskPanel BIT NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_showTaskPanel DEFAULT 0,
    lastReadMessageId UNIQUEIDENTIFIER NULL,
    unreadCount INT NOT NULL CONSTRAINT DF_DT_CHAT_MEMBER_unreadCount DEFAULT 0,
    CONSTRAINT PK_DT_CHAT_MEMBER PRIMARY KEY (roomId, nik),
    CONSTRAINT FK_DT_CHAT_MEMBER_room FOREIGN KEY (roomId) REFERENCES dbo.DT_CHAT_ROOM(id) ON DELETE CASCADE,
    CONSTRAINT FK_DT_CHAT_MEMBER_user FOREIGN KEY (nik) REFERENCES dbo.DT_USER(nik) ON DELETE CASCADE
  );
  CREATE INDEX IX_DT_CHAT_MEMBER_nik ON dbo.DT_CHAT_MEMBER(nik);
END;

IF OBJECT_ID('dbo.DT_CHAT_MESSAGE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DT_CHAT_MESSAGE (
    id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_DT_CHAT_MESSAGE PRIMARY KEY DEFAULT NEWID(),
    roomId UNIQUEIDENTIFIER NOT NULL,
    senderNik VARCHAR(20) NOT NULL,
    type VARCHAR(10) NOT NULL CONSTRAINT DF_DT_CHAT_MESSAGE_type DEFAULT 'text',
    content NVARCHAR(MAX) NOT NULL,
    taskRefJson NVARCHAR(MAX) NULL,
    replyToId UNIQUEIDENTIFIER NULL,
    reactionsJson NVARCHAR(MAX) NULL,
    readByJson NVARCHAR(MAX) NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_DT_CHAT_MESSAGE_createdAt DEFAULT SYSUTCDATETIME(),
    editedAt DATETIME2 NULL,
    deletedAt DATETIME2 NULL,
    CONSTRAINT FK_DT_CHAT_MESSAGE_room FOREIGN KEY (roomId) REFERENCES dbo.DT_CHAT_ROOM(id) ON DELETE CASCADE
  );
  CREATE INDEX IX_DT_CHAT_MESSAGE_room_created ON dbo.DT_CHAT_MESSAGE(roomId, createdAt);
  CREATE INDEX IX_DT_CHAT_MESSAGE_sender ON dbo.DT_CHAT_MESSAGE(senderNik);
END;

IF OBJECT_ID('dbo.DT_CHAT_PINNED_TASK', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.DT_CHAT_PINNED_TASK (
    roomId UNIQUEIDENTIFIER NOT NULL,
    taskId UNIQUEIDENTIFIER NOT NULL,
    projectId UNIQUEIDENTIFIER NOT NULL,
    projectName VARCHAR(100) NOT NULL,
    projectColor VARCHAR(30) NULL,
    name VARCHAR(100) NOT NULL,
    status BIT NOT NULL CONSTRAINT DF_DT_CHAT_PINNED_status DEFAULT 0,
    dueDate DATETIME2 NULL,
    pinnedAt DATETIME2 NOT NULL CONSTRAINT DF_DT_CHAT_PINNED_pinnedAt DEFAULT SYSUTCDATETIME(),
    pinnedBy CHAR(8) NOT NULL,
    CONSTRAINT PK_DT_CHAT_PINNED_TASK PRIMARY KEY (roomId, taskId),
    CONSTRAINT FK_DT_CHAT_PINNED_room FOREIGN KEY (roomId) REFERENCES dbo.DT_CHAT_ROOM(id) ON DELETE CASCADE,
    CONSTRAINT FK_DT_CHAT_PINNED_task FOREIGN KEY (taskId) REFERENCES dbo.DT_TASK(id) ON DELETE CASCADE
  );
  CREATE INDEX IX_DT_CHAT_PINNED_task ON dbo.DT_CHAT_PINNED_TASK(taskId);
END;
